services:
  - type: web
    name: flask-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: AC31c5efefe00cd49db254857ca9dc7c78
      - key: TWILIO_AUTH_TOKEN
        value: 89e36c493f8454528be409ec5560f8c9
      - key: MYSQL_HOST
        value: localhost
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: shruthi@123
      - key: MYSQL_DB
        value: campusbuzz
      - key: SECRET_KEY
        value: supersecretkey123